#' Set build releases
#'
#' This function generates new users and release lengths, calculates cumulative release lengths, 
#' and sets release dates for each build.
#'
#' @param builds A data frame of builds generated by the `get_builds` function.
#' @param new_users_max The maximum number of new users. This is used to generate a random number of new users for each build.
#' @param release_length_max The maximum release length. This is used to generate a random release length for each build.
#'
#' @return A data frame with the build numbers, new users, release dates, and release lengths.
#' @export
#' @importFrom dplyr mutate select
#' @importFrom lubridate date days
#' @importFrom magrittr %>%
#'
#' @examples
#' builds <- get_builds()
#' set_build_releases(builds, new_users_max = 100, release_length_max = 30) 

utils::globalVariables(c('release_length_cumulative',
    'release_length', 'build', 'new_users', 'release_date'))

set_build_releases <- function(builds, 
    new_users_max = 2, release_length_max = 7) {
  builds |> 
    dplyr::mutate(new_users = sample(0:new_users_max, nrow(builds),
                                     replace = TRUE),
                  release_length = sample(1:release_length_max, nrow(builds),
                                          replace = TRUE),
                  release_length_cumulative = cumsum(.data$release_length),
                  release_date = lubridate::date("2023-01-07") 
                    + lubridate::days(.data$release_length_cumulative)
                    - lubridate::days(.data$release_length)
    ) |>
    dplyr::select(build, new_users, release_date, release_length)
}