#' Set build releases
#'
#' This function generates new users and release lengths, calculates cumulative release lengths, 
#' and sets release dates for each build. Defaults to maximum length of 7 days.
#'
#' @param builds A data frame of builds generated by the `get_builds` function.
#' @param release_length_max The maximum release length. This is used to generate a random release length for each build.
#'
#' @return A data frame with the build numbers, new users, release dates, and release lengths.
#' @export
#' @importFrom dplyr mutate select
#' @importFrom lubridate date days
#' @importFrom magrittr %>%
#' 
#' @name set_build_releases
#'
#' @examples
#' builds <- get_versions()
#' set_build_releases(builds, release_length_max = 30) 

set_build_releases <- function(builds, release_length_max = 7) {
  builds |> 
    dplyr::mutate(
                  release_length = sample(1:release_length_max, nrow(builds),
                                          replace = TRUE),
                  release_length_cumulative = cumsum(release_length),
                  release_start = lubridate::date("2023-01-07") 
                    + lubridate::days(release_length_cumulative)
                    - lubridate::days(release_length),
                  release_end = release_start 
                    + lubridate::days(release_length)
                    - 1
    ) |>
    dplyr::select(build, release_length, release_start, release_end)
}